Домашняя работа
Grooter2023/AQA_MTS pull request #2
Opened 2023-11-17 19:39 UTC by Grooter2023

2023-11-20 21:55 UTC, wildpioneer requested changes

2023-11-20 21:55 UTC, wildpioneer commented on TypesAndOperators/Program.cs
> +            bool c = b == 0;
А почему эту проверку сразу не использовать в IF?

2023-11-20 21:55 UTC, wildpioneer commented on TypesAndOperators/Program.cs
> +        Console.ReadKey();
Это для чего?

2023-11-20 21:55 UTC, wildpioneer commented on TypesAndOperators/Program.cs
> +            if (a % 2 == 0)
Это аналогичный метод как до этого

2023-11-20 21:55 UTC, wildpioneer commented on TypesAndOperators/Program.cs
> +            switch (a % 2)
Технически это такой же метод - но за использование разных проверок - принимается

2023-11-22 19:18 UTC, Grooter2023 commented on TypesAndOperators/Program.cs
> +        Console.ReadKey();
Одним из наиболее распространенных способов [ReadKey()] использования метода является остановка выполнения программы до тех пор, пока пользователь не нажмет клавишу и приложение не завершит работу. Вот для этого его тут и использовала.

2023-11-22 19:20 UTC, Grooter2023 commented on TypesAndOperators/Program.cs
> +            bool c = b == 0;
См 1.1 можно и так и так реализовать.

2023-11-22 19:21 UTC, Grooter2023 commented on TypesAndOperators/Program.cs
> +            if (a % 2 == 0)
Верно, но теперь прописано в If. Реализовано по разному как просили в задании. Или я не верно поняла задание

2023-11-22 19:21 UTC, Grooter2023 commented on TypesAndOperators/Program.cs
> +            switch (a % 2)
Спасибо

2023-11-26 21:10 UTC, wildpioneer requested changes

2023-11-26 21:10 UTC, wildpioneer commented on TypesAndOperators/Program.cs
> +            bool c = b == 0;
Что такое 1.1 - никак не соображу?

2023-11-26 21:10 UTC, wildpioneer commented on TypesAndOperators/Program.cs
> +        Console.ReadKey();
А для чего нам останавливать программу?

2023-11-26 21:10 UTC, wildpioneer commented on TypesAndOperators/Program.cs
> +            if (a % 2 == 0)
По разному - имелось в виду не синтаксически - а разными способами. Ну пускай - можно списать на неверность задачи

2024-01-29 10:17 UTC, wildpioneer commented
Проверено

2024-01-29 10:17 UTC, closed without merging